[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "B6vhiae1UkbsLQnTsZf86qG2su3jJcBT4ZzQuewByMbW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kellenjames/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
